In [1]:
import torch
import torch.nn as nn
import numpy as np


Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
widenet = nn.Sequential(
    nn.Linear(2,4),
    nn.Linear(4,3)
)

deepnet = nn.Sequential(
    nn.Linear(2,2),
    nn.Linear(2,2),
    nn.Linear(2,3)
)

print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [3]:
for p in deepnet.named_parameters():
    print(p)
    print(' ')

('0.weight', Parameter containing:
tensor([[ 0.5420, -0.6334],
        [-0.2011,  0.4125]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([-0.0745,  0.5533], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[ 0.3058,  0.6522],
        [-0.4566, -0.3749]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.4030,  0.5050], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.3501,  0.1676],
        [ 0.1946, -0.3107],
        [ 0.5291, -0.6638]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([-0.3257,  0.1374, -0.3755], requires_grad=True))
 
