In [1]:
import torch
import torch.nn as nn
import numpy as np


Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
widenet = nn.Sequential(
    nn.Linear(2,4),
    nn.Linear(4,3)
)

deepnet = nn.Sequential(
    nn.Linear(2,2),
    nn.Linear(2,2),
    nn.Linear(2,3)
)

print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [3]:
for p in deepnet.named_parameters():
    print(p)
    print(' ')

('0.weight', Parameter containing:
tensor([[ 0.2843, -0.4676],
        [-0.6863,  0.1479]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([-0.1568,  0.3226], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[-0.3646, -0.2420],
        [-0.7023, -0.0985]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.2852, -0.0274], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[ 0.6583,  0.3020],
        [-0.1817,  0.5524],
        [ 0.6123,  0.3236]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([-0.4114,  0.0176,  0.2001], requires_grad=True))
 


In [4]:
# count the number of nodes
numNodesInWide = 0
for p in widenet.named_parameters():
    if 'bias' in p[0]:
        numNodesInWide += len(p[1])


numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
    if 'bias' in paramName:
        numNodesInDeep += len(paramVect)


print('There are %s nodes in the wide network' %numNodesInWide)
print('There are %s nodes in the deep network' %numNodesInDeep)

There are 7 nodes in the wide network
There are 7 nodes in the deep network


In [5]:
# just the parameters
for p in widenet.parameters():
    print(p)
    print(' ')

Parameter containing:
tensor([[-0.0007, -0.4727],
        [-0.4263,  0.3281],
        [-0.3237,  0.2185],
        [-0.4421, -0.4200]], requires_grad=True)
 
Parameter containing:
tensor([-0.5582,  0.0524, -0.4269,  0.6716], requires_grad=True)
 
Parameter containing:
tensor([[-0.0913,  0.0148,  0.2052, -0.0500],
        [ 0.1111,  0.3503, -0.2161, -0.4373],
        [-0.0655, -0.0807,  0.1223, -0.3779]], requires_grad=True)
 
Parameter containing:
tensor([ 0.4269, -0.3215,  0.0352], requires_grad=True)
 


In [6]:
# count the number of trainble parameters
nparams = 0
for p in widenet.parameters():
    if p.requires_grad:
        print('This piece has %s parameters' %p.numel())
        nparams += p.numel()

print('\n\nTotal parameters of %s parameters' %nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total parameters of 27 parameters


In [7]:
# list comprehension
nparams = np.sum([p.numel() for p in deepnet.parameters() if p.requires_grad])
print('Deepnet has  %s parameters'%nparams)

Deepnet has  21 parameters


In [10]:
!pip install torch-summary

In [12]:
from torchsummary import summary

summary(widenet, (1,2))

Layer (type:depth-idx)                   Output Shape              Param #
├─Linear: 1-1                            [-1, 1, 4]                12
├─Linear: 1-2                            [-1, 1, 3]                15
Total params: 27
Trainable params: 27
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00


Layer (type:depth-idx)                   Output Shape              Param #
├─Linear: 1-1                            [-1, 1, 4]                12
├─Linear: 1-2                            [-1, 1, 3]                15
Total params: 27
Trainable params: 27
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00