In [5]:
import numpy as np
import tensorflow as tf

In [3]:
print("Tensorflow version", tf.__version__)

Tensorflow version 2.12.0


# Tensors

Rank-0 tensor

In [5]:
t0 = tf.constant(0)
print(t0)

tf.Tensor(0, shape=(), dtype=int32)


Vector, rank 1.

In [7]:
t1 = tf.constant([0,1,2,3])
print(t1)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


Matrix rank 2

In [9]:
t2 = tf.constant([[1,2],
                  [3,4],
                  [5,6]], dtype=tf.float32)
print(t2)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)


Convert tensor to numpy array

In [12]:
n0 = t0.numpy()
n1 = t1.numpy()
n2 = t2.numpy()


In [15]:
a = tf.constant([[1,2],
                 [3,4]])
b = tf.constant([[1,1],
                 [1,1]])
print(tf.add(a,b))
print(tf.multiply(a,b))
print(tf.matmul(a,b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [28]:
c = tf.constant([[4.0, 5.0],
                 [10.0, 1.0]])
print(tf.reduce_max(c), "\n")
print(tf.math.argmax(c), "\n")
print(tf.nn.softmax(c), "\n")
print(tf.exp(c), "\n")
print(tf.exp(tf.constant([1], dtype=tf.float32)))
logits = tf.constant([1], dtype=tf.float32)

#softmax
ps = tf.exp(logits) / tf.reduce_sum(tf.exp(logits))

tf.Tensor(10.0, shape=(), dtype=float32) 

tf.Tensor([1 0], shape=(2,), dtype=int64) 

tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32) 

tf.Tensor(
[[5.4598148e+01 1.4841316e+02]
 [2.2026465e+04 2.7182817e+00]], shape=(2, 2), dtype=float32) 

tf.Tensor([2.7182817], shape=(1,), dtype=float32)


In [30]:
a = tf.constant([[1,2],
                 [3,4]])
b = tf.constant([[1,1],
                 [1,1]])

print(tf.add(a,b), '\n')
print(tf.multiply(a,b), '\n')
print(tf.matmul(a,b),'\n')

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [31]:
print(a + b, '\n')
print(a * b, '\n')
print(a @ b, '\n')

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [34]:
c = tf.constant([[4.0,5.0],[10.0,1.0]])
# Find maximum
print(tf.reduce_max(c))
# Index of maximum
print(tf.math.argmax(c))
# Softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [39]:
tf.convert_to_tensor([1,2,3])
tf.reduce_max([1,2,3])
tf.reduce_max(np.array([1,2,3]))

<tf.Tensor: shape=(), dtype=int64, numpy=3>

**Shape** Length of each axis
**Rank** Number of axes
**Axis** or **Dimension** A particular dimension
**Size** Total number of items in tensor (product of shape)

In [40]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

In [41]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


## Indexing
Indexes start at 0
negative indexes count backwards from end
colons are used for slices start:stop:step

# Variables


In [43]:
my_tensor = tf.constant([[1.0,2.0],[3.0,4.0]])
my_variable = tf.Variable(my_tensor)

bool_variable = tf.Variable([False, True])
complex_variable = tf.Variable([5+4j, 6+1j])

In [44]:
print("Shape: ", my_variable.shape)
print("DType: ", my_variable.dtype)
print("As NumPy: ", my_variable.numpy())

Shape:  (2, 2)
DType:  <dtype: 'float32'>
As NumPy:  [[1. 2.]
 [3. 4.]]


# Automatic Differentiation


In [3]:
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x**2

In [4]:
dy_dx = tape.gradient(y, x)
dy_dx.numpy()

6.0

In [6]:
w = tf.Variable(tf.random.normal((3,2)), name='w')
b = tf.Variable(tf.zeros(2, dtype=tf.float32), name='b')
x = [[1.,2.,3.]]

with tf.GradientTape(persistent=True) as tape:
    y = x @ w + b
    loss = tf.reduce_mean(y**2)

[dl_dw, dl_db] = tape.gradient(loss, [w,b])


In [8]:
print(w.shape)
print(dl_dw.shape)
print(dl_dw)

(3, 2)
(3, 2)
tf.Tensor(
[[0.8846216  0.37114185]
 [1.7692432  0.7422837 ]
 [2.6538649  1.1134255 ]], shape=(3, 2), dtype=float32)


In [ ]:
layer = tf.keras.layers.Dense(2, activation='relu')
x = tf.constant([1.,2.,3.])

with tf.GradientTape() as tape:
    y = layer(x)
    loss = tf.reduce_mean(y**2)

grad = tape.gradient(loss, layer.trainable_variables)

for var,g in zip(layer.trainable_variables, grad):
    print(f'{var.name}, shape: {g.shape}')

In [14]:
mnist = tf.keras.datasets.mnist

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [5]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [16]:
x_train, x_test = x_train/255.0, x_test/255.0

In [17]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


In [18]:
predictions = model(x_train[:1]).numpy()

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [19]:
predictions

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 4, 5], dtype=int32)>