# Loss Functions

`L1Loss` - Mean Absolute Error (MAE)

In [11]:
import torch
import torch.nn as nn

loss = nn.L1Loss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
#output.backward()
print(input)
print(target)
print(output)
print(input.grad)
print(output.backward())

i = torch.tensor([[1., 2., 3.], [4., 5., 6.]], requires_grad=True)
t = torch.tensor([[0., 1., 2.], [3., 4., 5.]])
o = loss(i, t)
print(o)
delta = torch.abs(i - t)
print(delta)

tensor([[-0.4671, -0.9228, -0.9067,  0.0081,  0.2449],
        [ 1.7616, -1.3756, -0.7164,  0.7715,  0.7248],
        [-0.9655,  1.1971, -0.5458, -1.4074, -0.6427]], requires_grad=True)
tensor([[ 0.5656,  1.0783,  1.0019, -1.1987, -1.2161],
        [-0.9970,  0.3744,  0.8165,  2.5514, -0.8201],
        [ 0.3276, -1.0930,  1.7484,  0.9336,  0.0459]])
tensor(1.7256, grad_fn=<MeanBackward0>)
None
None
tensor(1., grad_fn=<MeanBackward0>)
tensor([[1., 1., 1.],
        [1., 1., 1.]], grad_fn=<AbsBackward0>)
