In [2]:
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [4]:
a1 = np.array([1, 2, 3])
print("shape",a1.shape)
print("array",a1)
print("access -> ",a1[0])
a1_exp = np.expand_dims(a1, axis=1)
print("shape",a1_exp.shape)
print("array",a1_exp)
print("access -> ",a1_exp[0][0]) # now it is 2D array

shape (3,)
array [1 2 3]
access ->  1
shape (3, 1)
array [[1]
 [2]
 [3]]
access ->  1


In [17]:
a2 = np.array([[1, 2, 3]])
print("shape",a2.shape)

shape (1, 3)


In [10]:
a = np.array([
        [1, 2, 3], 
        [4, 5, 6]
    ])
print(a)
print(a.sum(axis=0)) # sum of each column
print(a.sum(axis=1)) # sum of each row
a.shape

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


(2, 3)

In [11]:
np.expand_dims(a, axis=0) # add a dimension of size 1 at index 0
a.shape # (2, 3)

(2, 3)