[Create Numpy Array](#create-numpy-array)
    [Range](#range)
[Array Attribute](#array-attribute)

Ordinary Python array

In [ ]:
my_list = [1,2,3]

In [3]:
import numpy as np

# Create Numpy Array
Import numpy, from now on you can use it.
Create a numpy array from python list.

6 ways how to create ndarray
Main datatype is ndarray

Create numpy array from normal array

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

Type of the numpy array is ndarray.

In [5]:
type(arr)

numpy.ndarray

Create a matrix (2d array) in python

In [111]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

And convert it to numpy array

In [112]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2D and 3D numpy arrays

In [ ]:
a2 = np.array(
    [
        [1,2.0,3],
        [4,5,6]
    ]
)

a3 = np.array(
    [
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ],
        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ]
    ]
)

## Range
Generating an array from range. Low index is inclusive high index it exclusive. Here we will get <0,10) array.

In [113]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Include step 2 (0,2,4 ...)

In [114]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Array of zeros with 3 elements

In [115]:
np.zeros(3)

array([0., 0., 0.])

Matrix of zeros 5x5

In [116]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [117]:
np.ones(3)

array([1., 1., 1.])

In [118]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [119]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [120]:
np.random.rand(4)

array([0.97828493, 0.41311166, 0.03155619, 0.90131914])

In [121]:
np.random.randn(4)

array([-1.06752159,  0.58666172, -1.7759762 ,  0.37114629])

In [122]:
np.random.randint(1,100,5)

array([34, 69, 55, 74, 38])

In [123]:
arr = np.random.randint(0,100,25)
arr.reshape(5,5)

array([[63, 48, 27, 60, 74],
       [68, 59, 12, 83,  0],
       [63, 20, 44, 66, 61],
       [91, 22, 88, 40, 76],
       [77,  6, 93, 52, 57]])

Returns a maximum along given axis

In [124]:
arr.max()

93

In [125]:
arr.min()

0

In [126]:
arr.argmax()

22

# Array Attribute
- Shape
- Dimension

In [127]:
arr.shape

(25,)

In [128]:
arr.dtype

dtype('int64')

In [129]:
arr[0]

63

In [130]:
arr[1:5]

array([48, 27, 60, 74])

In [131]:
arr[:5]

array([63, 48, 27, 60, 74])

In [132]:
arr[5:]

array([68, 59, 12, 83,  0, 63, 20, 44, 66, 61, 91, 22, 88, 40, 76, 77,  6,
       93, 52, 57])

In [133]:
arr[0:5] = 100

In [134]:
arr

array([100, 100, 100, 100, 100,  68,  59,  12,  83,   0,  63,  20,  44,
        66,  61,  91,  22,  88,  40,  76,  77,   6,  93,  52,  57])

In [135]:
slice_of_arr = arr[0:6]
slice_of_arr[:] = 99

In [136]:
arr

array([99, 99, 99, 99, 99, 99, 59, 12, 83,  0, 63, 20, 44, 66, 61, 91, 22,
       88, 40, 76, 77,  6, 93, 52, 57])

In [137]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99, 59, 12, 83,  0, 63, 20, 44, 66, 61, 91, 22,
       88, 40, 76, 77,  6, 93, 52, 57])

In [138]:
arr_copy[:] = 100

In [139]:
arr_2d = np.array([[5,10,5],[20,25,20],[35,45,35]])

In [140]:
arr_2d[0][0]
arr_2d[0]

array([ 5, 10,  5])

In [141]:
arr_2d[2,2]

35

In [142]:
arr_2d[:2,1:]

array([[10,  5],
       [25, 20]])

In [143]:
arr = np.arange(1,11)

In [144]:
bool_arr = arr > 5

In [145]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [146]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [147]:
arr[arr < 3]

array([1, 2])

In [148]:
arr = np.arange(0,11)

In [149]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [150]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [151]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [152]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [153]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [154]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [155]:
arr.max()

10

In [156]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])