# Matrices

- [Addition and Substraction](#Addition-and-subtraction)
- [Shifting](#Shifting)
- [Multiply by scalar](#multiply-by-scalar)
- [Transpose](#transpose)

Matrices are a rectangular array of numbers. They are used to represent linear transformations.

Matrix types:

- Square (NxN)
- Rectangular (MxN)
- Symmetric (is squared)
- Skew Symmetric (opposite numbers acros diagonal)
- Identity (all 1 on diagonal, 0 otherwise) -  square and symmetric
- Zero (all zeros)
- Diagonal (non-zero on diagonal, otherwise 0)
- Upper triangular
- Lower triangular
- Concatenated 

In [18]:
import numpy as np

S = np.random.randint(1,10,(3,3)) # square
R = np.random.randint(1,10,(3,2)) # rectangular
print(S)
print(' ')
print(R, '\n')

print('=======================')

# Identity - square matrix with ones on the diagonal
I = np.eye(3)
print('Identity')
print(I, '\n')
print('=======================')

# Zeros - all zeros
print('Zeros')
Z = np.zeros((3,3))
print(Z, '\n')
print('=======================')
# diagonal - square matrix with specified diagonal
print('Diagonal')
D = np.diag([1,2,3])
print(D, '\n')

[[1 4 8]
 [6 6 6]
 [2 6 5]]
 
[[4 8]
 [8 2]
 [1 6]] 

Identity
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

Diagonal
[[1 0 0]
 [0 2 0]
 [0 0 3]] 



In [11]:
import numpy as np
# triangular
S = np.random.randint(1,10,(3,3))
U = np.triu(S) # upper triangular
L = np.tril(S) # lower triangular
print(U, '\n')
print(L, '\n')

# Concatenate matrices
A = np.random.randint(1,10,(3,4))
B = np.random.randint(1,10, (3,4))
C = np.concatenate((A,B), axis=1)
print(C, '\n')

[[4 4 2]
 [0 4 4]
 [0 0 5]] 

[[4 0 0]
 [1 4 0]
 [9 6 5]] 

[[4 3 3 1 3 9 7 1]
 [8 5 3 7 2 2 7 9]
 [7 3 6 3 8 3 4 7]] 



Symmetric matrix:

$$ A = \begin{bmatrix} 1 & 2 & 3 \\ 2 & 4 & 5 \\ 3 & 5 & 6 \end{bmatrix} $$

$$ A = A^T $$

In [16]:
import numpy as np  
# Transpose
A = np.array([[1,2,3],[2,4,5],[3,5,6]])
print(A, '\n')
print(A.T, '\n')

[[1 2 3]
 [2 4 5]
 [3 5 6]] 

[[1 2 3]
 [2 4 5]
 [3 5 6]] 



## Addition and subtraction
Add or subtract the corresponding elements.
Matrices must have the same dimensions.

Commutative and associative

$$ A + B = B + A$$
$$ A + (B + C) = (A + B) + C $$


## Shifting
Multiply identity matrix by a scalar

$A + \lambda I = C $

In [15]:
import numpy as np

A = np.random.randint(1,10, (5,4)) # 5x4
B = np.random.randint(1,10, (5,3)) # 5x3
C = np.random.randint(1,10, (5,4)) # 5x4

#A+B # error - not same shape
A+C # ok - same shape

array([[14, 11,  5,  6],
       [ 5, 14,  9,  7],
       [10,  9, 10,  4],
       [10, 14,  6,  7],
       [ 6, 16, 13, 12]])

In [16]:
import numpy as np
# shifting matrix
l = .3
N = 4
D = np.random.randint(1,10, (N,N)) # can only shift square matrix

Ds = D + l * np.eye(N) # shift diagonal
print(D)
print(' ')
print(Ds)

[[8 4 5 8]
 [5 5 5 8]
 [5 6 2 8]
 [8 4 3 6]]
 
[[8.3 4.  5.  8. ]
 [5.  5.3 5.  8. ]
 [5.  6.  2.3 8. ]
 [8.  4.  3.  6.3]]


## Multiply by scalar
Multiply every element by scalar.

$\delta MA = M\delta A = MA\delta $

In [7]:
import numpy as np
M = np.array([ [1,2], [2,5]])
s = 2
print(M*s)
print(s*M)

[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


## Transpose
First row become first column

$A^{TT} = A$

In [9]:
M = np.array([
    [1,2,3],
    [2,3,4]
])

print(M)
print(' ')
print(M.T)
print(' ')
print(M.T.T)
print(' ')
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]
 
[[1 2]
 [2 3]
 [3 4]]
 
[[1 2 3]
 [2 3 4]]
 
[[1 2]
 [2 3]
 [3 4]]


## Diagonal and trace
Trace is sum of all diagonal elements. Trace is defined only for square matrices.

Diagonal 

$v_i = A_{i,i} , i = \{ 1,2,...,min(m,n)\}$

Trace

$ tr(A) = \Sigma_{i=1}^m A_{i,i}$

In [11]:
M = np.round(5*np.random.randn(4,4))

d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix

print(d)
print(D)

tr = np.trace(M)
tr2 = sum(np.diag(M))
print(tr, tr2)


[-5. -2.  2.  5.]
[[-5.  0.  0.  0.]
 [ 0. -2.  0.  0.]
 [ 0.  0.  2.  0.]
 [ 0.  0.  0.  5.]]
0.0 0.0


## Broadcasting


In [17]:
A = np.reshape(np.arange(1,13),(3,4),'F') # F-column, C=row

r = [10,20,30,40]
c = [100,200,300]
print(A), print(' ')
print(r), print(' ')
print(c), print(' ')

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[10, 20, 30, 40]
 
[100, 200, 300]
 


(None, None)

In [22]:
# broadcast on the rows
print(A+r), print(' ') # illegal in normal linear algebra

# broadcast on the colums
# print(A+c) # does not work on columns
# reshape to column vector
print(A + np.reshape(c, (len(c),1)))

[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]


## Frobenius Norm

$$ ||A||_F = \sqrt{\Sigma_{i=1}^m \Sigma_{j=1}^n A_{i,j}^2} $$

Measure of size of matrix in Euclidean space.
It is the sum of magnitude of all the vectors in the matrix.

In [13]:
import numpy as np
import torch

X = np.array([[1,2],[3,4]])
Fnorm = (1**2 + 2**2 + 3**2 + 4**2)**.5
print(Fnorm)
Fnorm_np = np.linalg.norm(X)
print(Fnorm_np)
Fnorm_t = torch.norm(torch.tensor(X, dtype=torch.float))
print(Fnorm_t.item())

5.477225575051661
5.477225575051661
5.4772257804870605


## Inverse
Matrix inverse is a matrix that gives identity matrix when multiplied by original matrix.
$$ A^{-1}A = AA^{-1} = I $$

Solution of
$$ Ax = b $$
is
$$ A^{-1}Ax = A^{-1}b $$
$$ Ix = A^{-1}b $$
$$ x = A^{-1}b $$

In [3]:
import numpy as np

A = np.array([[4,2],[-5,-3]])
Ainv = np.linalg.inv(A)
b = np.array([[4],[-7]])
x = np.dot(Ainv,b)
x

array([[-1.],
       [ 4.]])