# Addition and subtraction
Add or subtract the corresponding elements.
Matrices must have the same dimensions.

Commutative and associative

$$ A + B = B + A$$
$$ A + (B + C) = (A + B) + C $$


## Shifting
Multiply identity matrix by a scalar

$A + \lambda I = C $

In [2]:
import numpy as np

A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

A+B # error
A+C

array([[ 0.46741913,  2.51815595,  0.31276976, -2.42199553],
       [ 0.04922817, -0.66974715,  0.02595042,  1.14599757],
       [ 0.84633978,  0.54000226,  2.20968744,  2.39101166],
       [ 1.15872376, -0.76445295,  3.68437215,  3.76865855],
       [ 0.54007979,  0.95235479,  2.29805521,  0.87125431]])

In [6]:
# shifting matrix
l = .3
N = 4
D = np.random.randn(N,N) # can only shift square matrix

Ds = D + l * np.eye(N)
print(D)
print(' ')
print(Ds)

[[-0.26463083 -0.89588622  0.56791313 -0.21024336]
 [ 0.03597213 -0.03680255  0.27260118 -0.78825242]
 [ 0.05064755 -0.61345504  0.60943831  0.17403148]
 [-0.78516681 -0.86595057 -1.97158025  0.57991567]]
 
[[ 0.03536917 -0.89588622  0.56791313 -0.21024336]
 [ 0.03597213  0.26319745  0.27260118 -0.78825242]
 [ 0.05064755 -0.61345504  0.90943831  0.17403148]
 [-0.78516681 -0.86595057 -1.97158025  0.87991567]]


## Multiply by scalar
Multiply every element by scalar.

$\delta MA = M\delta A = MA\delta $

In [7]:
M = np.array([ [1,2], [2,5]])
s = 2
print(M*s)
print(s*M)

[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


## Transpose
First row become first column

$A^{TT} = A$

In [9]:
M = np.array([
    [1,2,3],
    [2,3,4]
])

print(M)
print(' ')
print(M.T)
print(' ')
print(M.T.T)
print(' ')
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]
 
[[1 2]
 [2 3]
 [3 4]]
 
[[1 2 3]
 [2 3 4]]
 
[[1 2]
 [2 3]
 [3 4]]


## Diagonal and trace
Trace is sum of all diagonal elements. Trace is defined only for square matrices.

Diagonal 

$v_i = A_{i,i} , i = \{ 1,2,...,min(m,n)\}$

Trace

$ tr(A) = \Sigma_{i=1}^m A_{i,i}$

In [11]:
M = np.round(5*np.random.randn(4,4))

d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix

print(d)
print(D)

tr = np.trace(M)
tr2 = sum(np.diag(M))
print(tr, tr2)


[-5. -2.  2.  5.]
[[-5.  0.  0.  0.]
 [ 0. -2.  0.  0.]
 [ 0.  0.  2.  0.]
 [ 0.  0.  0.  5.]]
0.0 0.0


## Broadcasting


In [17]:
A = np.reshape(np.arange(1,13),(3,4),'F') # F-column, C=row

r = [10,20,30,40]
c = [100,200,300]
print(A), print(' ')
print(r), print(' ')
print(c), print(' ')

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[10, 20, 30, 40]
 
[100, 200, 300]
 


(None, None)

In [22]:
# broadcast on the rows
print(A+r), print(' ') # illegal in normal linear algebra

# broadcast on the colums
# print(A+c) # does not work on columns
# reshape to column vector
print(A + np.reshape(c, (len(c),1)))

[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
