In [1]:
import numpy as np

In [4]:
a1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
np.transpose(a1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
# Broadcast
x = np.array([[1],[2],[3]])
y = np.array([4,5,6])
z = np.broadcast(x,y)

In [11]:
z.shape

(3, 3)

In [12]:
# 2x2 2x1 => 2x1
# 5 + 12 = 17
# 15 + 24 = 39
x = np.array([[1,2],
              [3,4]])
y = np.array([5,6])
np.matmul(x,y)

array([17, 39])

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.multiply(a,b)

In [14]:
c

array([ 4, 10, 18])

In [15]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[1,2],
              [3,4]])
c = np.multiply(a,b)

In [16]:
c

array([[ 1,  4],
       [ 9, 16]])

In [17]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[1,2],
              [3,4]])
c = np.multiply(a,b)
c_t = np.transpose(c)
a_t = np.transpose(a)
b_t = np.transpose(b)
d_t = np.multiply(a_t, b_t)

In [18]:
c_t

array([[ 1,  9],
       [ 4, 16]])

In [19]:
d_t

array([[ 1,  9],
       [ 4, 16]])